services:
  gitea:
    image: gitea/gitea:1.20.5-rootless
    restart: unless-stopped
    volumes:
      - /docker/gitea/data:/var/lib/gitea
      - /docker/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:2222"

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /docker/homarr/configs:/app/data/configs
      - /docker/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'


  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /docker/syncthing/config:/config
      - /docker/syncthing/data1:/data1
      - /docker/syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'

    volumes:
      - /docker/nginx-proxy-manager/data:/data
      - /docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  vaultwarden:
    restart: unless-stopped
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - /docker/vaultwarden/:/data/
    ports:
      - 8062:80
    environment:
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://warden.izanagi.xyz
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true

  sws:
    image: joseluisq/static-web-server
    container_name: static-web-server
    restart: unless-stopped
    ports:
      - 8787:80
    volumes:
      - /home/ubuntu/public:/public

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8081:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/docker/nextcloud
      - NEXTCLOUD_MEMORY_LIMIT=1024M

  mc:
    image: itzg/minecraft-server
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      MODRINTH_PROJECTS: lithium,vmp-fabric,c2me-fabric,ferrite-core,krypton,modernfix,chunky,starlight,fabric-api,lazydfu,journeymap
      MOTD: "§4§lZen's §6§lServer"
      ICON: "https://oshi.at/oDGP"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      MEMORY: "8G"
      OPS: zen
      SERVER_NAME: "Zen's Server"
      SIMULATION_DISTANCE: "16"
      USE_AIKAR_FLAGS: "TRUE"
      SYNC_CHUNK_WRITES: "FALSE"
      VIEW_DISTANCE: "16"
      SPAWN_PROTECTION: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      ENABLE_STATUS: "TRUE"
      ONLINE_MODE: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
    restart: unless-stopped
    volumes:
      - /docker/minecraft/data:/data

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
