version: '2'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    restart: unless-stopped
    volumes:
      - /docker/roundmail/www:/var/www/html
      - /docker/roundmail/config:/var/roundcube/config
      - /docker/roundmail/db/sqlite:/var/roundcube/db
      - /docker/roundmail/tmp:/tmp/roundcube-temp
    ports:
      - 9002:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_SMTP_PORT=465
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.izanagi.xyz
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.izanagi.xyz
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
