version: "3.3"

services:
  web:
    image: joseluisq/static-web-server
    container_name: static-web-server
    restart: unless-stopped
    ports:
      - 8787:80
    volumes:
      - /home/ubuntu/public:/public
