version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - /home/ubuntu/dashy/my-config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
